# Generated by Django 4.1.7 on 2023-03-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('mail', models.CharField(max_length=50)),
                ('line_id', models.CharField(max_length=50)),
            ],
        ),
    ]
