# Generated by Django 3.2.18 on 2023-05-22 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerlinebot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry_interior',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ministry_interior',
            name='time',
        ),
        migrations.RemoveField(
            model_name='ministry_interior',
            name='url',
        ),
        migrations.AddField(
            model_name='ministry_interior',
            name='inform_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
