# Generated by Django 4.1.7 on 2023-04-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerlinebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry_Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('line_id', models.CharField(max_length=50)),
            ],
        ),
    ]
