# Generated by Django 3.2.18 on 2023-06-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerlinebot', '0002_auto_20230607_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry_interior',
            name='inform_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='post_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
